encoder_odom_publisher:
    ros__parameters:
        use_sim_time: true
        
        # Joint names from /joint states that we are publishing from our USD file.
        left_wheel_joint: "joint_wheel_left"
        right_wheel_joint: "joint_wheel_right"
        
        # Frames 
        odom_frame: "odom"
        base_frame: "chassis_link"
        
        # Robot Geometry (meter) [Noted from the Nova Carter properties and calculated wheel distance]
        wheel_radius: 0.14
        wheel_separation: 0.4132
        
        publish_tf: true
        odom_topic: "/odom"
